config/routes.rb
Rails.application.routes.draw do
  get '/cart' => 'cart#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :items
  resources :users
  resources :categories
  resources :subcategories
  get 'items/new', to: 'items#new'
  post 'items/create', to: 'items#create'
  patch 'new', to: 'items#new'
  patch 'delete', to: 'items#delete'
  get 'profile', to: 'users#profile', as: 'profile'
  root :to =>'home#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    belongs_to :user
    has_many :items 
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :subcategory
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :items
  has_one :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
 class CartController < ApplicationController
  def index
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
	    @category = Category.find(params[:id])

	    respond_to do |format|
	        format.html # show.html.erb
	        format.xml { render :xml => @category }
	    end
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@user=current_user
		@items = Item.all
		@categories = Category.all
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new
    @item.name = params[:item][:name]
    @item.description = params[:item][:description]
    @item.price = params[:item][:price]
    @item.user = current_user
    if @item.valid?
      @item.save
      redirect_to '/items'
    else
      flash[:error] = @item.errors.full_messages.to_sentence
      redirect_to '/items/new'
    end
  end

  def delete
    item_to_delete = Item.find(params[:id])
    item_to_delete.destroy
    redirect_to '/items'
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
	def show
	    @subcategory = Subcategory.find(params[:id])

	    respond_to do |format|
	        format.html # show.html.erb
	        format.xml { render :xml => @subcategory }
	    end
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def show
    @user = User.find(params[:id])

    respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end
  end
  def profile
    @user = current_user

    respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/cart/index.html.erb
<h1>Cart#index</h1>
<p>Find me in app/views/cart/index.html.erb</p>

app/views/categories/show.html.erb
<%= link_to "All", '/' %> > <%= @category.name %>

<div class='container'>
     <% Subcategory.where(category_id: @category).in_groups_of(6, false).each do |group| %>
          <div class="row subCategoryRow">
            <% group.each do |subcategory| %>
               <%= link_to(subcategory) do %>
                   <div class="box col-md-2">
                         <%= subcategory.name %>
                    </div>
               <% end %>
            <% end %>
          </div>
     <% end %>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>

<h2>Welcome <%= current_user.first_name %>!</h2>

<% else %>

<h2> Welcome! Please sign in! </h2>

<% end %>
<div class='container'>
	<% @categories.in_groups_of(4, false).each do |group| %>
		<div class="row categoryRow">
		  <% group.each do |category| %>
			<%= link_to(category) do %>
			    <div class="box col-md-3">
					<%= category.name %>
				</div>
			<% end %>
		  <% end %>
		</div>
	<% end %>
</div>

app/views/items/index.html.erb
<%= button_to "Add Item", new_path, :class => "addButton", :method => :patch %>
<% @items.each do |i| %>
	<div class="item">
		<span class="item-title"> <%= i.name %> </span>
		<p>Seller: <%= i.user.email %><br>
		Description: <%= i.description %><br>
		Price: <%= i.price %></p>
		<%= button_to "Delete", delete_path(id: i), :class => "button medium", :method => :patch %>
	</div>
<% end %>

app/views/items/new.html.erb
<%= simple_form_for @item, :url => '/items/create' do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/_header.html.erb
<header class="nav-wrapper">
	<div class="logo md col-xs-4 col-sm-4 col-md-4">
		<a href="/"><%= image_tag("cart.svg", :alt => "CART") %><img></a>
		<!-- <a href="/"><img src="cart.svg"><img></a> -->
	</div>
	<div class="mobile-menu"></div>
	<div class="nonmobile-menu col-sm-8 col-md-8">
		<ul class="main-menu">
			<% if user_signed_in? %>
				<li><%= link_to "All Items", '/items' %></li>
				<li><%= link_to "Profile", profile_path %></li>
				<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
			<% else %>
				<li><%= link_to "Home", '/items' %></li>
				<li><%= link_to "Sign In", new_user_session_path, :method => :get %></li>
				<li><%= link_to "Sign up", new_user_registration_path, :method => :get %></li>
			<% end %>
		</ul>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Proj2</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
			<!-- <%= debug(params) if Rails.env.development? %> -->
	    </div>
	    <%= render 'layouts/footer' %>
	</body>
</html>

app/views/subcategories/show.html.erb
<%= link_to "All", '/' %>
> 
<% category=Category.find(@subcategory.category_id) %>
<%= link_to(category) do %>
<%= category.name%>
<% end %>
>
<%= @subcategory.name %>

<div class='container'>
	<% Item.where(subcategory_id: @subcategory).in_groups_of(6, false).each do |group| %>
	  <div class="row subCategoryRow">
	    <% group.each do |item| %>
	       <div class="item">
	       		<span class="item-title"> <%= item.name %> </span>
	       		<p>Seller: <%= item.user.email %><br>
	       		Description: <%= item.description %><br>
	       		Price: <%= item.price %></p>
	       		<%= button_to "Delete", delete_path(id: item), :class => "button medium", :method => :patch %>
	       	</div>
	    <% end %>
	  </div>
	<% end %>
</div>

app/views/users/profile.html.erb
<div class="profileContainer">
	<ul>
		<li><%= current_user.first_name %></li>
		<li><%= link_to "Settings", edit_user_registration_path %></li>
	</ul>
</div>

app/views/users/show.html.erb
<%= @user.first_name %>